version: '3.7'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - '3001:3000'
    volumes:
      - .:/app
